services:

  backend:
    build: .
    env_file:
      - .configs/env
    platform: linux/amd64
    ports:
      - 8080:8080
    networks:
      - live-view-network
    command: bash -c "./src/App"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=liveview
      - POSTGRES_PASSWORD=liveview
      - POSTGRES_DATABASE=liveview
    ports:
      - 5432:5432
    networks:
      - live-view-network

  pg-admin:
    image: dpage/pgadmin4:snapshot
    ports:
      - 8000:8000
    environment:
      - PGADMIN_DEFAULT_EMAIL=liveview@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=liveview
    networks:
      - live-view-network
  
networks:
  live-view-network:
    driver: bridge